# Generated by Django 4.2.6 on 2023-10-27 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='curso',
            field=models.ForeignKey(default='Curso', on_delete=django.db.models.deletion.CASCADE, to='core.curso', verbose_name='Curso'),
        ),
    ]
